image: ubuntu:16.04

before_script:
  - sudo apt-get update
  - sudo apt-get install -y  wget docker

build-musl-plain:
  tags:
    - virtualbox-runner
  stage: build
  script:
    - docker stack deploy -c scope.yml SCOPE
    - wget http://localhost:4040 | wc -l
    - docker stack rm SCOPE

