image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - sudo apt-get update
  - sudo apt-get install -y  wget make

run-SCOPE-stack:
  tags:
    - virtualbox-runner
  stage: build
  script:
    - make ci

