image: ubuntu:16.04

before_script:
  - apt-get update
  - apt-get install -y docker wget

build-musl-plain:
  tags:
    - docker-runner
    - docker-sock
  stage: build
  script:
    - docker stack deploy -c scope.yml SCOPE
    - wget http://localhost:4040 | wc -l
    - docker stack rm SCOPE

