image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - sudo apt-get update
  - sudo apt-get install -y  wget

run-SCOPE-stack:
  tags:
    - virtualbox-runner
  stage: build
  script:
    - sudo SCONE_HOSTINSTALLER/install_patched_docker.sh
    - sudo docker swarm init
    - sudo docker stack deploy -c scope.yml SCOPE
    - sleep 5
    - wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 2 http://$IP:4040
    - sudo docker stack rm SCOPE

