image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - sudo apt-get update
  - sudo apt-get install -y  wget

run-SCOPE-stack:
  tags:
    - virtualbox-runner
  stage: build
  script:
    - sudo SCONE_HOSTINSTALLER/install_patched_docker.sh
    - sudo docker swarm init
# change user has not taken effect - run with sudo
    - sudo ./start-scope.sh
    - sleep 5
    - IP=`hostname -I | awk '{print $1;}'`
    - sudo docker ps -a
    - sudo docker stack ps SCOPE
    - sudo docker ps -a
    - wget --retry-connrefused --waitretry=1 --read-timeout=30 --timeout=15 -t 25 http://localhost:4040
    - sudo ./stop-scope.sh

