image: ubuntu:16.04

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - sudo apt-get update
  - sudo apt-get install -y  wget

run-SCOPE-stack:
  tags:
    - virtualbox-runner
  stage: build
  script:
    - sudo ./install_patched_docker.sh
    - sudo docker swarm init
    - sudo docker stack deploy -c scope.yml SCOPE
    - sleep 5
    - wget http://localhost:4040 || echo "Upps"
    - sudo docker stack rm SCOPE

