version: '3'
services:
  scope:
    image: weaveworks/scope:release-1.5-1667984
    # network_mode: "host"

    pid: "host"
    # privileged: true

    ports:
      - 4040:4040

    labels:
      - "works.weave.role=system"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"

    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      depends_on:
      - memcached      

    command:
      - "--probe.docker=true"
      - "-app.memcached.hostname memcached-1"


  memcached:
    image: memcached
    ports:
      - "11211:11211"

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
