version: '3'
services:
  scope:
    image: weaveworks/scope:latest
    # network_mode: "host"

    pid: "host"
    # privileged: true

    ports:
      - 4040:4040

    labels:
      - "works.weave.role=system"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"

    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      
    command:
      - "--probe.docker=true"
      - "-weave"

